version: 2.1

orbs:
  # Replace this with your own!
  terraform: circleci/terraform@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  validate-command-sequence:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: "src/infra"
      - terraform/fmt:
          path: "src/infra"
      - terraform/validate:
          path: "src/infra"
      - terraform/plan:
          path: "src/infra"
          workspace: "orb-testing"
      - terraform/apply:
          path: "src/infra"
          workspace: "orb-testing"
      - terraform/destroy:
          path: "src/infra"
          workspace: "orb-testing"
  validate-terraform-install:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - terraform/install


workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      # optional: Run BATS tests against your scripts
      # - bats/run:
      #     path: ./src/tests
      # If you accept building open source forks, protect your secrects behind a restricted context.
      # A job containing restricted context (which holds your orb publishing credentials) may only be accessed by a user with proper permissions.
      # An open source user may begin a pipeline with a PR, and once the pipeline is approved by an authorized user at this point, the pipeline will continue with the proper context permissions.
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            # - bats/run
            - shellcheck/check
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: circleci/terraform
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires: [hold-for-dev-publish]
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - validate-command-sequence:
          context: Terraform-orb-testing
      - validate-terraform-install
      - terraform/init:
          cli_config_file: "foo"
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - validate-command-sequence
            - validate-terraform-install
      - terraform/fmt:
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - terraform/init
      - terraform/validate:
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - terraform/fmt
      - terraform/plan:
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - terraform/validate
      - terraform/apply:
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - terraform/plan
      - hold-destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          context: Terraform-orb-testing
          checkout: true
          path: "src/infra"
          requires:
            - hold-destroy
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          context: orb-publishing
          orb-name: circleci/terraform
          ssh-fingerprints: 45:59:71:c6:c2:66:86:3f:7c:78:30:1b:ed:7d:f0:8d
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          requires:
            - validate-command-sequence
            - terraform/init
            - terraform/fmt
            - terraform/validate
            - terraform/plan
            - terraform/apply
            - terraform/destroy
          filters:
            branches:
              only: master
